### ISSUE TITLE
Logger: Implementing default logger provided by @nestjs/common

### ISSUE THREAD

**Issue by sp-sandeshpokhrel** [sp-sandeshpokhrel/Nestjs_app#15]

**Comment by rakimsth** [comment]
@sp-sandeshpokhrel , 
Please try to implement the logger on the following cases:
1. On App initialization
2. On Services Initialization (Prisma, redis, mailer, AWS, Google)etc
3. Log all the significant contexts (Db write, redis write, Operation success, Operation failure)
4. Don’t Log Sensitive Information (roles, user info, system info)
